feature/folder and loading files created and working
C5Team3/front-end pull request #59
Opened 2020-10-28 18:55 UTC by sergiohortua

2020-10-29 15:20 UTC, alfredomtzg commented on src/components/Loading/index.jsx
> +export const Loading2 = () => {
Can be use export default const Loading2 and change the name to Loading

2020-10-29 15:21 UTC, alfredomtzg commented on src/containers/App.jsx
> +      <Loading2/>
delete this component in App.jsx

2020-10-29 15:23 UTC, alfredomtzg commented on src/containers/App.jsx
delete this import because it is likely to conflict with develop branch

2020-10-29 15:23 UTC, alfredomtzg commented on src/containers/App.jsx
> +import {Loading2} from '../components/Loading/index'
delete this import because it is likely to conflict with develop branch

2020-10-29 15:24 UTC, alfredomtzg requested changes
check the comments

2020-10-29 19:19 UTC, alfredomtzg approved these changes

2020-10-31 13:07 UTC, shukonin approved these changes

2020-10-31 13:07 UTC, merged